services:
  vissionarie:
    image: vissionarie
    ports:
      - '8080:8080'
  vissionarie-mongodb-node:
    build:
      context: src\main\docker
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --shardsvr --replSet rs1
  vissionarie-mongodb-config:
    image: mongo:4.4.10
    container_name: vissionarie-mongodb-config
    command: mongod --configsvr --dbpath /data/db --replSet csvr
  vissionarie-mongodb:
    image: mongo:4.4.10
    command: mongos --configdb csvr/vissionarie-mongodb-config --bind_ip 0.0.0.0

  prometheus:
    image: prom/prometheus:v2.31.1
    volumes:
      - ./prometheus-conf/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  alertmanager:
    image: prom/alertmanager:v0.23.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager-conf/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana:8.2.4
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  prometheus_data: {}
  grafana_data: {}
